apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j2o3kuf06-python
  janus-idp.io/tekton: j2o3kuf06-python
  backstage.io/kubernetes-id: j2o3kuf06-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j2o3kuf06-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
